name: Cypress Test and Report

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Necesario para poder hacer push a GitHub Pages

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Cypress Run (headed Chrome)
        id: cypress
        run: npx cypress run --browser chrome --headed || true  # Ejecuta Cypress en modo headed

      - name: Generate Cucumber HTML Report
        run: node cucumber-html-report.js

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Puedes ajustar según lo que necesites

      - name: Deploy Cucumber Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/chrome

      - name: Create Cucumber HTML Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: ./cypress/reports/chrome


