name: Cypress Test and Report

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Necesario para poder hacer push a GitHub Pages

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Ajusta según necesidad

      - name: Install Dependencies
        run: npm install

      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Run Cypress headed with Xvfb
        env:
          DISPLAY: :99
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 3
          npx cypress run --headed || true

      - name: Generate Cucumber HTML Report
        run: node cucumber-html-report.js

      - name: Deploy Cucumber Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/chrome

      - name: Create Cucumber HTML Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: ./cypress/reports/chrome

